---
name: Fuse-PDF
version: 0.01
author:
  - 'Chris Dolan <cdolan@cpan.org>'
abstract: Filesystem embedded in a PDF document
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CAM::PDF: 1.00
  Fuse: 0.08
  Readonly: 0
  perl: 5.6.0
build_requires:
  Test::Class: 0
  Test::More: 0.62
recommends:
  Getopt::Long: 2.0
  Pod::Usage: 1.0
  Test::Memory::Cycle: 1.02
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Fuse::PDF:
    file: lib/Fuse/PDF.pm
    version: 0.01
  Fuse::PDF::FS:
    file: lib/Fuse/PDF/FS.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
